
GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTU4NzY2MTQsImV4cCI6MTcxNTg4MDIxNCwiYXVkIjoiNjY0NWVlN2U2MmJkMGQwZmM3ZWJjN2JiIiwiaXNzIjoicmVjaGkuY29tIn0.QPgwy0lHSM7bA-bmP1M0K1ul1aZZyxRJYlcXIP3j3H4

### login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "Rechi18@gmail.com",
    "password": "Alexwhite96"
}
### register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "Rechi22@gmail.com",
    "password": "Alexwhite96"
}
### refres token route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTU4NzY2MTQsImV4cCI6MTc0NzQzNDIxNCwiYXVkIjoiNjY0NWVlN2U2MmJkMGQwZmM3ZWJjN2JiIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.tsr30sKX8t9pIhG3ZjwWY_sWmAeBDuUex75c1_6P1ck"
}

### logout route
DELETE http://localhost:3000/auth/logout