
GET http://localhost:3000
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTU4NzY2MTQsImV4cCI6MTcxNTg4MDIxNCwiYXVkIjoiNjY0NWVlN2U2MmJkMGQwZmM3ZWJjN2JiIiwiaXNzIjoicmVjaGkuY29tIn0.QPgwy0lHSM7bA-bmP1M0K1ul1aZZyxRJYlcXIP3j3H4

### login route
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "Rechi19@gmail.com",
    "password": "Alexwhite96"
}
### register route
POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "email": "Rechi24@gmail.com",
    "password": "Alexwhite96"
}
### refres token route
POST http://localhost:3000/auth/refresh-token
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYyNTgyMDIsImV4cCI6MTc0NzgxNTgwMiwiYXVkIjoiNjY0YzA1OWE4Y2QzNWY2NzZkYjMyMmJlIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.p4Ww_dfPS2r8O-Z19HTD7ACIe0kPuu5wXw-LgLhHS6A"
}

### logout route
DELETE http://localhost:3000/auth/logout
Content-Type: application/json

{
    "refreshToken": "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpYXQiOjE3MTYyNTgyMzAsImV4cCI6MTc0NzgxNTgzMCwiYXVkIjoiNjY0YzA1OWE4Y2QzNWY2NzZkYjMyMmJlIiwiaXNzIjoicGlja3VycGFnZS5jb20ifQ.ZoR0A3MDjVjf3p912zRevwT-_ap11h6TaxBGkP6KCRE"
}